// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"realworld/internal/biz"
	"realworld/internal/conf"
	"realworld/internal/data"
	"realworld/internal/server"
	"realworld/internal/service"
	"realworld/pkg/dbresolver"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	resolver, err := dbresolver.NewResolver()
	if err != nil {
		return nil, nil, err
	}
	repo := data.NewRepo(resolver)
	bizBiz := biz.NewBiz(repo)
	realWorldService := service.NewRealWorldService(bizBiz)
	httpServer := server.NewHTTPServer(confServer, realWorldService, logger)
	grpcServer := server.NewGRPCServer(confServer, realWorldService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
